apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/bharath-b-rh/konflux-samples?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "pull_request" && target_branch
      == "main" && (".tekton/cert-manager-operator-pull-request.yaml".pathChanged() ||
      "Containerfile.cert-manager-operator".pathChanged() || "cert-manager-operator/***".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: konflux-samples
    appstudio.openshift.io/component: cert-manager-operator
    pipelines.appstudio.openshift.io/type: build
  name: cert-manager-operator-on-pull-request
  namespace: bhb-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/bhb-tenant/cert-manager-operator:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: Containerfile.cert-manager-operator
    - name: path-context
      value: .
    - name: build-args
      value:
        - RELEASE_VERSION=v1.16.0
        - COMMIT_SHA={{revision}}
        - SOURCE_URL={{source_url}}
  pipelineRef:
    resolver: git
    params:
      - name: url
        value: https://github.com/bharath-b-rh/konflux-shared-configs.git
      - name: revision
        value: main
      - name: pathInRepo
        value: .tekton/multi-arch-build-pipeline.yaml
  taskRunTemplate:
    serviceAccountName: build-pipeline-cert-manager-operator
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
